### ISSUE TITLE
Is H1 appropriate markup for search result titles?

### ISSUE THREAD

**Issue by rwd** [europeana/Europeana-Patternlab#16]
In the Search templates, both grid and list views, each result title is in an H1 element.

In my opinion, they should not be in any heading element, but if they are, it should not be an H1.

Within the structure of a page, surely they are not at the same hierarchical content level as the main site title "Europeana Collections"?

**Comment by DavidHaskiya** [comment]
Agreed, they should be H2s. No page should ever have more than one H1. Bad
SEO.

**Comment by andyjmaclean** [comment]
Fixed
