### ISSUE TITLE
Use consistent variable name formatting

### ISSUE THREAD

**Issue by rwd** [europeana/Europeana-Patternlab#4]
The templates use an assortment of different styles of variable naming:

* filters.items.is-checked (hyphenated)
* filters.items.num_results (underscored)
* searchresults.objectUrl (camelcased)

They should use just one of these formats.

My preference is for underscored, but most important is consistency.

**Comment by timharbour** [comment]
yep, will endeavour to do better. I think most use underscores and that's what we should be using.
the is-checked is a hang over from the css where i use hyphens.
I'll fix the stuff in filters.
