### ISSUE TITLE
Omit "Europeana News" heading if there is no news

### ISSUE THREAD

**Issue by rwd** [europeana/Europeana-Patternlab#5]
On the portal home page and channels landing pages, blog posts should be displayed, but may not be.

If they are not, i.e. there are none supplied to the templates by the application, then the heading "Europeana News" should be omitted. Contrast with the current situation where it is displayed with no news items beneath:

![screenshot_2015-07-21_09-59-50](https://cloud.githubusercontent.com/assets/218337/8796838/bee3696c-2f8f-11e5-8e41-032d60ca21d4.png)

**Comment by timharbour** [comment]
hey, 
The news section markup will only output if the content.news object exists.
If there are no items to display then we need to stop outputting the content.news object.

**Comment by rwd** [comment]
@timharbour right you are, addressing in the app then.
